version: '3.8'
services:
  # hbase:
  #   build:
  #     dockerfile: hbase.Dockerfile
  #   ports:
  #     - '8080:8080'
  #     - '8085:8085'
  #     - '9090:9090'
  #     - '9095:9095'
  #   environment:
  #     - HBASE_INIT_SCHEMA_FILE=/initdb/hbase-schema.txt
  #     - HBASE_INITDB_FILE=/initdb/clean-books-sep.csv
  #   volumes:
  #     - ./data:/initdb:ro

  db:
    image: postgres:15.2
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres-volume:
