version: '3.8'

services:
  hbase:
    build:
      dockerfile: hbase.Dockerfile
    ports:
      - '2181:2181'
      - '4000:4000'
      - '8080:8080'
      - '8085:8085'
      - '9090:9090'
      - '9095:9095'
    environment:
      - HBASE_INIT_SCHEMA_FILE=/initdb/hbase-schema.txt
      - HBASE_INITDB_FILE=/initdb/books_hbase.csv
    volumes:
      - ./data:/initdb:ro
      # - ./bookstore-dbms/target:/app:ro

  # hdfs:
  #   image: enzo90910/multiarch-hadoop-singlenode:3.3.0
  #   ports:
  #     - '9870:9870'
  #     - '8088:8088'
  #     - '4040:4040'
  #     - '18080:18080'
  #   networks:
  #     - hdfs-network

  db:
    image: postgres:15.2-alpine3.17
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - '8081:8080'

volumes:
  postgres-volume:
